services:
#    dugun_upload.example:
#        class: Dugun\UploadBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    dugun_upload.service.upload_service:
        class: Dugun\UploadBundle\Service\UploadService
        arguments: ['%dugun_upload.config%']